org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# https://modrinth.com/mod/fabric-api/versions
# https://modrinth.com/mod/fabric-language-kotlin/versions
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

java_version=25
java_version.26.2=25

mod_version=1.0.0
maven_group=csz

fabric_api_version=0.160.0+26.2
cloth_config_version=26.1.154
